name: 'CI'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  unit-tests:
    uses: ./.github/workflows/ci-unit.yml

  integration-tests:
    uses: ./.github/workflows/ci-integration.yml

  lint-build:
    uses: ./.github/workflows/ci-check.yml

  deploy:
    needs: [unit-tests, integration-tests, lint-build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  e2e-tests:
    needs: [deploy]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/ci-e2e.yml
    secrets: inherit
